modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/FifouBE/EconomyInc/issues" #optional
credits="FifouBE, MarcusSlover"
license="All right reserved"

[[mods]] #mandatory
	modId="economyinc" #mandatory
	version="1.8" #mandatory
	displayName="Economy Inc." #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/economy-inc" #optional
	description='''
	DESCRIPTION
	'''