modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/FifouBE/EconomyInc/issues"
[[mods]]
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/economy-inc"
logoFile="economyinc.png"
authors="${mod_authors}" 
description='''${mod_description}'''
